show_room/core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('category/cardigan', views.cardigan_view, name='cardigan_index'),
    path('category/pullover', views.pullover_view, name='pullover_index'),
    path('category/vest', views.vest_view, name='vest_index'),
    path('category/gender/male', views.male_view, name='male_index'),
    path('category/gender/female', views.female_view, name='female_index'),
    path('category/gender/kids', views.kids_view, name='kids_index'),
]

show_room/merchant/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('merchant/', views.index, name='merchant_index')
]

show_room/product/urls.py
from django.urls import path
from . import views


app_name='product'
urlpatterns = [
    path('', views.index, name='product_index'),
    path('product/<int:id>', views.details, name='product_details'),
    path("search/", views.SearchResultView.as_view(), name='search'),
]

show_room/show_room/urls.py
import merchant
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = 'Showroom | Meek'
admin.site.site_title = 'Showroom | Meek'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('', include('core.urls')),
    path('', include('merchant.urls'))
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

show_room/category/models.py
from django.db import models


class Category(models.Model):
    CHOICE_FIELD = (
        ('cardigan', "Cardigan"),
        ('pullover', "Pullover"),
        ('vest', "Vest")
    )
    category_name = models.CharField(choices=CHOICE_FIELD, max_length=34, null=True, blank=True)
    category_image = models.ImageField(default='default.jpg', upload_to='product/category')

    class Meta():
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category_name

show_room/core/models.py
from django.db import models

# Create your models here.

show_room/gender/models.py
from django.db import models


class Gender(models.Model):
    CHOICE_FIELD = (
        ('male', "Male"),
        ('female', "Female"),
        ('boys', "Boys"),
        ('girls', "Girls"),
        ('unisex', "Unisex"),
    )
    gender_name = models.CharField(choices=CHOICE_FIELD, max_length=34, null=True, blank=True)
    gender_image = models.ImageField(default='default.jpg', upload_to='product/gender')

    def __str__(self):
        return self.gender_name

show_room/merchant/models.py
import merchant
from django.db import models


class Merchant(models.Model):
    merchant_name = models.CharField(max_length=55)
    merchant_designation = models.CharField(max_length=55)
    merchant_mobile = models.CharField(max_length=21)
    merchant_email = models.EmailField()
    merchant_join_date = models.DateField(auto_now_add=False)
    merchant_image = models.ImageField(default='default.jpg', upload_to='product/merchant')

    def __str__(self):
        return self.merchant_name

show_room/product/models.py
from django.db import models
from gender.models import Gender
from category.models import Category
from merchant.models import Merchant


# Create your models here.
class Product(models.Model):
    product_style = models.CharField(max_length=21)
    product_composition = models.CharField(max_length=144)
    product_gauge = models.CharField(max_length=13)
    product_size = models.CharField(max_length=13)
    product_weight = models.CharField(max_length=13)
    product_moq = models.CharField(max_length=13)
    product_fob = models.CharField(max_length=13)
    product_category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default="-")
    product_gender = models.ForeignKey(Gender, on_delete=models.SET_DEFAULT, default="-")
    product_merchant = models.ForeignKey(Merchant, on_delete=models.SET_DEFAULT, default="Admin")
    product_buyer = models.IntegerField(default=0)
    product_shipment_date = models.DateField(auto_now_add=False)
    product_quantity = models.IntegerField(default=0)
    product_image = models.ImageField(default='default.jpg', upload_to='product/pro')
    product_chart = models.ImageField(default='default.jpg', upload_to='product/chart')

    def __str__(self):
        return self.product_style

show_room/category/views.py
from django.shortcuts import render

# Create your views here.

show_room/core/views.py
from django.shortcuts import render
from django.db.models import Q
from product.models import Product


def cardigan_view(request):
    query = 'cardigan'
    cardigans = Product.objects.filter(
        Q(product_category__category_name__exact=query)
    )
    return render(request, 'product/core/cardigan/cardigan_list.html', {'products': cardigans})


def pullover_view(request):
    query = 'pullover'
    pullover = Product.objects.filter(
        Q(product_category__category_name__exact=query)
    )
    return render(request, 'product/core/pullover/pullover_list.html', {'products': pullover})


def vest_view(request):
    query = 'vest'
    vest = Product.objects.filter(
        Q(product_category__category_name__exact=query)
    )
    return render(request, 'product/core/vest/vest_list.html', {'products': vest})


def male_view(request):
    query = 'male'
    male = Product.objects.filter(
        Q(product_gender__gender_name__exact=query)
    )
    return render(request, 'product/core/gender/male_list.html', {'products': male})


def female_view(request):
    query = 'female'
    female = Product.objects.filter(
        Q(product_gender__gender_name__exact=query)
    )
    return render(request, 'product/core/gender/female_list.html', {'products': female})


def kids_view(request):
    query = 'kids'
    kids = Product.objects.filter(
        Q(product_gender__gender_name__exact=query)
    )
    return render(request, 'product/core/gender/kids_list.html', {'products': kids})

show_room/gender/views.py
from django.shortcuts import render

# Create your views here.

show_room/merchant/views.py
from django.shortcuts import render
from .models import Merchant


def index(request):
    merchants = Merchant.objects.all()
    return render(request, 'product/merchant/index.html', {'merchants': merchants})

show_room/product/views.py
from product.models import Product
from django.shortcuts import render
from django.views.generic import ListView
from .models import Product
from category.models import Category
from django.db.models import Q


def index(request):
    products = Product.objects.all()
    return render(request, 'product/product.html', {'products': products})


def details(request, id):
    product = Product.objects.get(id=id)
    return render(request, 'product/product_details.html', {'product': product})


# Search from navbar
class SearchResultView(ListView):
    model = Product
    template_name = 'product/search_result.html'

    def get_queryset(self):
        category = Category.objects.all()
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
            Q(product_style__icontains=query) | Q(product_composition__icontains=query) |
            Q(product_gauge__icontains=query) | Q(product_size__icontains=query) |
            Q(product_weight__icontains=query) | Q(product_moq__icontains=query) |
            Q(product_fob__icontains=query) | Q(product_category__category_name__icontains=query) |
            Q(product_gender__gender_name__icontains=query)
        )

        return object_list

show_room/product/templates/product/core/cardigan/cardigan_list.html
{% extends 'product/master.html' %}
{% load static %}

{% block main %}
    
  <main id="main">

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">

        <div class="section-title mt-3 mb-0 p-0" data-aos="fade-up">
          <h2>Cardigan's</h2>
        </div>

        <div class="row justify-content-center">
          {% for product in products %}
            <div class="col-lg-4 col-md-6 align-items-stretch">
              <div class="card" id='product-card'>
                <a href="{% url 'product:product_details' product.id %}">
                <img style='weight: 233pt; height: 233pt;' class='card-img-top' src="{{ product.product_image.url }}" alt="" srcset=""></a>
                <h4 class='mt-1 text-center mb-0'><a href="{% url 'product:product_details' product.id %}">{{product.product_style}}</a></h4>
                <p class='text-center'><a href="{% url 'product:product_details' product.id %}">{{product.product_composition}}</a></p>
              </div>
              <br>
            </div>
            
          {% endfor %}
        </div>

      </div>
    </section><!-- End Services Section -->

  </main><!-- End #main -->

{% endblock main %}

{% block script %}
   
{% endblock script %}

show_room/product/templates/product/core/gender/female_list.html
{% extends 'product/master.html' %}
{% load static %}

{% block main %}
    
  <main id="main">

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">

        <div class="section-title mt-3 mb-0 p-0" data-aos="fade-up">
          <h2>Female Product's</h2>
        </div>

        <div class="row justify-content-center">
          {% for product in products %}
            <div class="col-lg-4 col-md-6 align-items-stretch">
              <div class="card" id='product-card'>
                <a href="{% url 'product:product_details' product.id %}">
                <img style='weight: 233pt; height: 233pt;' class='card-img-top' src="{{ product.product_image.url }}" alt="" srcset=""></a>
                <h4 class='mt-1 text-center mb-0'><a href="{% url 'product:product_details' product.id %}">{{product.product_style}}</a></h4>
                <p class='text-center'><a href="{% url 'product:product_details' product.id %}">{{product.product_composition}}</a></p>
              </div>
              <br>
            </div>
            
          {% endfor %}
        </div>

      </div>
    </section><!-- End Services Section -->

  </main><!-- End #main -->

{% endblock main %}

{% block script %}
   
{% endblock script %}

show_room/product/templates/product/core/gender/kids_list.html
{% extends 'product/master.html' %}
{% load static %}

{% block main %}
    
  <main id="main">

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">

        <div class="section-title mt-3 mb-0 p-0" data-aos="fade-up">
          <h2>Kid's Product's</h2>
        </div>

        <div class="row justify-content-center">
          {% for product in products %}
            <div class="col-lg-4 col-md-6 align-items-stretch">
              <div class="card" id='product-card'>
                <a href="{% url 'product:product_details' product.id %}">
                <img style='weight: 233pt; height: 233pt;' class='card-img-top' src="{{ product.product_image.url }}" alt="" srcset=""></a>
                <h4 class='mt-1 text-center mb-0'><a href="{% url 'product:product_details' product.id %}">{{product.product_style}}</a></h4>
                <p class='text-center'><a href="{% url 'product:product_details' product.id %}">{{product.product_composition}}</a></p>
              </div>
              <br>
            </div>
            
          {% endfor %}
        </div>

      </div>
    </section><!-- End Services Section -->

  </main><!-- End #main -->

{% endblock main %}

{% block script %}
   
{% endblock script %}

show_room/product/templates/product/core/gender/male_list.html
{% extends 'product/master.html' %}
{% load static %}

{% block main %}
    
  <main id="main">

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">

        <div class="section-title mt-3 mb-0 p-0" data-aos="fade-up">
          <h2>Male Product's</h2>
        </div>

        <div class="row justify-content-center">
          {% for product in products %}
            <div class="col-lg-4 col-md-6 align-items-stretch">
              <div class="card" id='product-card'>
                <a href="{% url 'product:product_details' product.id %}">
                <img style='weight: 233pt; height: 233pt;' class='card-img-top' src="{{ product.product_image.url }}" alt="" srcset=""></a>
                <h4 class='mt-1 text-center mb-0'><a href="{% url 'product:product_details' product.id %}">{{product.product_style}}</a></h4>
                <p class='text-center'><a href="{% url 'product:product_details' product.id %}">{{product.product_composition}}</a></p>
              </div>
              <br>
            </div>
            
          {% endfor %}
        </div>

      </div>
    </section><!-- End Services Section -->

  </main><!-- End #main -->

{% endblock main %}

{% block script %}
   
{% endblock script %}

show_room/product/templates/product/core/vest/vest_list.html
{% extends 'product/master.html' %}
{% load static %}

{% block main %}
    
  <main id="main">

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">

        <div class="section-title mt-3 mb-0 p-0" data-aos="fade-up">
          <h2>Vest's</h2>
        </div>

        <div class="row">
          {% for product in products %}
            <div class="col-lg-4 col-md-6 align-items-stretch">
              <div class="card" id='product-card'>
                <a href="{% url 'product:product_details' product.id %}">
                <img style='weight: 233pt; height: 233pt;' class='card-img-top' src="{{ product.product_image.url }}" alt="" srcset=""></a>
                <h4 class='mt-1 text-center mb-0'><a href="{% url 'product:product_details' product.id %}">{{product.product_style}}</a></h4>
                <p class='text-center'><a href="{% url 'product:product_details' product.id %}">{{product.product_composition}}</a></p>
              </div>
              <br>
            </div>
            
          {% endfor %}
        </div>

      </div>
    </section><!-- End Services Section -->

  </main><!-- End #main -->

{% endblock main %}

{% block script %}
   
{% endblock script %}

show_room/product/templates/product/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock title%}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href=" {% static 'img/favicon.png' %} " rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/venobox/venobox.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: #fffff0">

{% include 'product/partials/_header.html' %}

  {% block main %}{% endblock main %}

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'vendor/jquery-sticky/jquery.sticky.js' %}"></script>
  <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>
  {% block script %}{% endblock script %}
  
</body>

</html>

show_room/product/templates/product/partials/_header.html
  <!-- ======= Header ======= -->
  <header id="header" style="background-color: #fffff0">
    <div class="container d-flex ">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="{% url 'product:product_index'%}"><span>MEEK</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu d-none d-lg-block ">
        <ul>
          <li class="active"><a href="{% url 'product:product_index'%}">Home</a></li>

          <li class="drop-down"><a href="#">Category</a>
            <ul>
              <li><a href="{% url 'cardigan_index' %}">Cardigan</a></li>
              <li><a href="{% url 'pullover_index' %}">Pullover</a></li>
              <li><a href="{% url 'vest_index' %}">Vest</a></li>


              <li class="drop-down"><a href="#"> Gender </a>
                <ul>
                  <li><a href="{% url 'male_index' %}">Male</a></li>
                  <li><a href="{% url 'female_index' %}">Female</a></li>
                  <li><a href="{% url 'kids_index' %}">Kids</a></li>
                </ul>
              </li>
            </ul>
          </li>

          <li><a href="{% url 'merchant_index' %}">Merchant</a></li>
          <li><a href="portfolio.html">Buyer</a></li>
          <li><a href="{% url 'admin:index'%}">Admin</a></li>
          <li class='m-1 ml-2'>
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'product:search' %}">
              <input class="form-control mr-sm-2" name="q" type="search" placeholder=" " aria-label="Search">
              <button class="btn btn-secondary my-2 my-sm-0 p-2" type="submit">Search</button>
            </form>
          </li>
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->

show_room/product/templates/product/product.html
{% extends 'product/master.html' %}
{% load static %}

{% block main %}
    
  <main id="main">

    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
      <div class="container">

        <div class="section-title mt-3 mb-0 p-0" data-aos="fade-up">
          <h2>Our Latest Product's</h2>
        </div>

        <div class="row justify-content-center">
          {% for product in products %}
            <div class="col-lg-4 col-md-6 align-items-stretch">
              <div class="card" id='product-card' data-aos="fade-up">
                <a href="{% url 'product:product_details' product.id %}">
                <img style='weight: 233pt; height: 233pt;' class='card-img-top' src="{{ product.product_image.url }}" alt="" srcset=""></a>
                <h4 class='mt-1 text-center mb-0'><a href="{% url 'product:product_details' product.id %}">{{product.product_style}}</a></h4>
                <p class='text-center'><a href="{% url 'product:product_details' product.id %}">{{product.product_composition}}</a></p>
              </div>
              <br>
            </div>
            
          {% endfor %}
        </div>

      </div>
    </section><!-- End Services Section -->

  </main><!-- End #main -->

{% endblock main %}

{% block script %}
   
{% endblock script %}

show_room/product/templates/product/product_details.html
{% extends 'product/master.html' %}
{% load static %}

{% block main %}
    
  <main id="main">

    <!-- ======= Body Section ======= -->
    <section id="services" class="services">
      <div class="container">

        <div class="row mt-5">
            <div class="col-lg-5 col-md-5 align-items-stretch">
                <div class="card ">
                    <img style='weight: 233pt; height: 233pt;' class='card-img-top' src="{{ product.product_image.url }}" alt="" srcset="">
                </div>
            </div>

            <div class="col-lg-7 col-md-7">
              <div class="section-title mt-3 mb-0 p-0" data-aos="fade-up">
                <h2>{{product.product_style}}</h2>
              </div>
              <blockquote class="blockquote text-center">
                <p class="mb-0">Baby girls pullover long sleeve</p>
                <footer class="blockquote-footer">{{product.product_composition}} <cite title="Source Title"> By Meek Sweater & Fashions Ltd.</cite></footer>
              </blockquote>
            </div>
        </div>
        <br>

        <table class="table">
          <thead class="thead-dark table-sm text-center">
            <tr>
              <th scope="col">Composition</th>
              <th scope="col">Merchant</th>
              <th scope="col">Buyer</th>
              <th scope="col">Category</th>
              <th scope="col">Shipment</th>
              <th scope="col">Quantity</th>
              <th scope="col">Gauge</th>
              <th scope="col">Size</th>
              <th scope="col">Weight</th>

            </tr>
          </thead>
          <tbody class='text-center'>
            <tr>
              <td>{{product.product_composition}}</td>
              <td>{{product.product_merchant}}</td>
              <td>{{product.product_buyer}}</td>
              <td>{{product.product_category}}</td>
              <td>{{product.product_shipment_date}}</td>
              <td>{{product.product_quantity}}</td>
              <td>{{product.product_gauge}}</td>
              <td>{{product.product_size}}</td>
              <td>{{product.product_weight}}</td>
            </tr>
          </tbody>
        </table>

      </div>
    </section><!-- End Section -->

  </main><!-- End #main -->

{% endblock main %}

show_room/product/templates/product/search_result.html
{% extends 'product/master.html' %}


{% block main %}

    <div class="container mt-5">
        <div class="row justify-content-center">
            {% for product in object_list %}
                <div class="col-md-4 col-sm-4">
                        <div class="card" style="" >
                            <a href="{% url 'product:product_details' product.id%}" style="text-decoration:none">
                            <img class="card-img-top" src={{product.product_image.url}} alt="{{product.product_style}}" style="width:100%" width="21rem" height="233rem">
                            <div class="card-body">
                                <h4 class="card-title font-weight-bolder text-dark" style="font-size: 13pt; margin-top: -5pt;">{{product.product_style}}</h4>
                                <p class="card-text text-dark" style="font-size: 13pt; margin-top: -5pt;">{{product.product_composition}}</p>
                            </div>
                        </div>
                        <br>
                    </a>
                </div>
            {% empty %}
                <div class="jumbotron text-center">
                    No product found
                </div>
            {% endfor %}
        </div>
        <br>
    </div>


{% endblock main %}