online_newspaper/category/urls.py
from django.conf.urls import url
from . import views


app_name = 'category'
urlpatterns = [
    url(r'^panel/category/add/$', views.category_add, name='category-add'),
    url(r'^panel/category/list/$', views.category_list, name='category-list'),
]

online_newspaper/main/urls.py
from django.conf.urls import url
from . import views


app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='main-index'),
    url(r'^panel/$', views.panel, name='admin-panel'),
    url(r'^about/$', views.about, name='main-about'),
]

online_newspaper/news/urls.py
from django.conf.urls import url
from . import views


app_name='news'
urlpatterns = [
    url(r'^news/(?P<pk>\d+)/$', views.news_details, name='news-details'),
    url(r'^panel/news/list/$', views.news_list, name='news-list'),
    url(r'^panel/news/add/$', views.news_add, name='news-add'),
    url(r'^panel/news/del/(?P<pk>\d+)/$', views.news_delete, name='news-delete'),
    url(r'^panel/news/edit/(?P<pk>\d+)/$', views.news_edit, name='news-edit'),
]

online_newspaper/online_newspaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('news.urls')),
    path('', include('category.urls')),
    path('', include('subcategory.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_newspaper/subcategory/urls.py
from django.conf.urls import url
from . import views


app_name = 'subcategory'
urlpatterns = [
    url(r'^panel/subcategory/add/$', views.subcategory_add, name='subcategory-add'),
    url(r'^panel/subcategory/list/$', views.subcategory_list, name='subcategory-list'),
]

online_newspaper/main/models.py
from __future__ import unicode_literals
from django.db import models


class Main(models.Model):
    name = models.CharField(max_length=21)
    fb = models.CharField(default='-', max_length=21)
    tw = models.CharField(default='-', max_length=21)
    yt = models.CharField(default='-', max_length=21)
    contact = models.CharField(default='-', max_length=21)
    about = models.TextField(default='-')

    set_name = models.CharField(default='Site Settings', max_length=21)

    def __str__(self):
        return self.set_name + " | " + str(self.pk)

online_newspaper/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Main
from news.models import News


def index(request):
    site = Main.objects.all()
    news = News.objects.all()
    return render(request, 'front/main/index.html', {'site': site, 'news': news})


def panel(request):
    return render(request, 'back/index.html')


def about(request):
    return render(request, 'front/main/about.html')

online_newspaper/main/templates/back/category_add.html
    {% extends 'back/master.html' %}
    {% load static %}

    {% block body %}
        <!-- Page content -->
        <div id="page-content">
            <!-- Datatables Content -->
            <div class="block full">
                <div class="block-title">
                    <h2><strong>Category</strong> Add</h2>
                </div>
                <p>You can Add a news article from here.</p>
                <!-- Input Grid Content -->
                    <form action="{% url 'category:category-add' %}" method="post" enctype='multipart/form-data' class="form-horizontal form-bordered">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-8">
                                <input type="text" id='category_name' name='category_name' class="form-control" placeholder="Category Name">
                            </div>

                            <div class="col-xs-4">
                                <button type="submit" class="btn btn-block btn-primary">Submit</button>
                            </div>
                        </div>
                        
                    </form>
                    <!-- END Input Grid Content -->  
            </div>
            <!-- END Datatables Content -->
        </div>
        <!-- END Page Content -->
    {% endblock body %}

        
    {% block javascript %}
        <!-- Load and execute javascript code used only in this page -->
        <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
        <script>$(function(){ TablesDatatables.init(); });</script>
    {% endblock javascript %}
        
    

online_newspaper/main/templates/back/category_list.html
    {% extends 'back/master.html' %}
    {% load static %}

    {% block body %}
        <!-- Page content -->
        <div id="page-content">
            <!-- Datatables Content -->
            <div class="block full">
                <div class="block-title">
                    <h2><strong>Category</strong> List</h2>
                </div>
                <p>You can add, delete, edit your category.</p>

                <div class="table-responsive">
                    <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                        <thead>
                            <tr >
                                <th class="text-center">ID</th>
                                <th class='text-center'>Title</th>
                                <th class='text-center'>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for category in category %}
                            <tr>
                                <td class="text-center">{{category.pk}}</td>
                                <td class='text-center'>{{category.name}}</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-xs btn-default"><i class="fa fa-pencil"></i></a>
                                        <a href="" data-toggle="tooltip" title="Delete" class="btn btn-xs btn-danger"><i class="fa fa-times"></i></a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}    
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END Datatables Content -->
        </div>
        <!-- END Page Content -->
    {% endblock body %}

        
    {% block javascript %}
        <!-- Load and execute javascript code used only in this page -->
        <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
        <script>$(function(){ TablesDatatables.init(); });</script>
    {% endblock javascript %}
        
    

online_newspaper/main/templates/back/error.html
    {% extends 'back/master.html' %}
    {% load static %}

    {% block body %}
        <!-- Page content -->
        <div id="page-content">
            <!-- Datatables Content -->
            <div class="block full">
                <div class="block-title">
                    <h2><strong>Error</strong> Adding</h2>
                </div>
                <p>Error happed during form submission.</p>
                <p>{{error}}</p>
            </div>
            <!-- END Datatables Content -->
        </div>
        <!-- END Page Content -->
    {% endblock body %}

        
    {% block javascript %}
        <!-- Load and execute javascript code used only in this page -->
        <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
        <script>$(function(){ TablesDatatables.init(); });</script>
    {% endblock javascript %}
        
    

online_newspaper/main/templates/back/index.html
{% extends 'back/master.html' %}
{% load static %}

{% block body %}
    <!-- Mini Top Stats Row -->
    <div class="row">
        <div class="col-sm-6 col-lg-3">
            <!-- Widget -->
            <a href="page_ready_article.html" class="widget widget-hover-effect1">
                <div class="widget-simple">
                    <div class="widget-icon pull-left themed-background-autumn animation-fadeIn">
                        <i class="fa fa-file-text"></i>
                    </div>
                    <h3 class="widget-content text-right animation-pullDown">
                        New <strong>Article</strong><br>
                        <small>Mountain Trip</small>
                    </h3>
                </div>
            </a>
            <!-- END Widget -->
        </div>
        <div class="col-sm-6 col-lg-3">
            <!-- Widget -->
            <a href="page_comp_charts.html" class="widget widget-hover-effect1">
                <div class="widget-simple">
                    <div class="widget-icon pull-left themed-background-spring animation-fadeIn">
                        <i class="gi gi-usd"></i>
                    </div>
                    <h3 class="widget-content text-right animation-pullDown">
                        + <strong>250%</strong><br>
                        <small>Sales Today</small>
                    </h3>
                </div>
            </a>
            <!-- END Widget -->
        </div>
        <div class="col-sm-6 col-lg-3">
            <!-- Widget -->
            <a href="page_ready_inbox.html" class="widget widget-hover-effect1">
                <div class="widget-simple">
                    <div class="widget-icon pull-left themed-background-fire animation-fadeIn">
                        <i class="gi gi-envelope"></i>
                    </div>
                    <h3 class="widget-content text-right animation-pullDown">
                        5 <strong>Messages</strong>
                        <small>Support Center</small>
                    </h3>
                </div>
            </a>
            <!-- END Widget -->
        </div>
        <div class="col-sm-6 col-lg-3">
            <!-- Widget -->
            <a href="page_comp_gallery.html" class="widget widget-hover-effect1">
                <div class="widget-simple">
                    <div class="widget-icon pull-left themed-background-amethyst animation-fadeIn">
                        <i class="gi gi-picture"></i>
                    </div>
                    <h3 class="widget-content text-right animation-pullDown">
                        +30 <strong>Photos</strong>
                        <small>Gallery</small>
                    </h3>
                </div>
            </a>
            <!-- END Widget -->
        </div>
        
    </div>
    <!-- END Mini Top Stats Row -->
{% endblock body %}

{% block javascript %}
    <!-- Load and execute javascript code used only in this page -->
    <script src="{% static 'back/js/pages/index.js' %}"></script>
    <script>$(function(){ Index.init(); });</script>
{% endblock javascript %}

online_newspaper/main/templates/back/news_add.html
    {% extends 'back/master.html' %}
    {% load static %}

    {% block headblock %}
        <script src="{% static 'back/ckeditor/ckeditor.js' %}"></script>
    {% endblock headblock %}
    
    {% block body %}
        <!-- Page content -->
        <div id="page-content">
            <!-- Datatables Content -->
            <div class="block full">
                <div class="block-title">
                    <h2><strong>News</strong> Add</h2>
                </div>
                <p>You can Add a news article from here.</p>
                <!-- Input Grid Content -->
                    <form action="{% url 'news:news-add' %}" method="post" enctype='multipart/form-data' class="form-horizontal form-bordered">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-8">
                                <input type="text" id='newstitle' name='newstitle' class="form-control" placeholder="News Title">
                            </div>
                            <div class="col-md-4">
                                <select id="newscat" name="newscat" class="select-chosen" data-placeholder="Category" style="width: 250px;">
                                    {% for option in subcategory %}
                                        <option value="{{option.pk}}">{{option.category_name}} | {{option.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea type="text" id='newstxtshort' name='newstxtshort' rows=5 class="form-control" placeholder="Short Text"></textarea>
                            </div>

                        </div>
                        <script>
                            CKEDITOR.replace('newstxtshort');
                        </script>

                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea type="textarea" id='newstxtlong' name='newstxtlong' rows=5 class="form-control" placeholder="Body Text"></textarea>
                            </div>
                        </div>
                        <script>
                            CKEDITOR.replace('newstxtlong');
                        </script>

                        <div class="form-group">
                            <div class="col-md-12">
                                <input type="file" id='myfile' name='myfile' class="form-control" placeholder="Body Text">
                            </div>
                        </div>
                        
                        <div class="form-group form-actions">
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-block btn-secondary">Submit</button>
                            </div>
                        </div>

                        
                    </form>
                    <!-- END Input Grid Content -->  
            </div>
            <!-- END Datatables Content -->
        </div>
        <!-- END Page Content -->
    {% endblock body %}

        
    {% block javascript %}
        <!-- Load and execute javascript code used only in this page -->
        <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
        <script>$(function(){ TablesDatatables.init(); });</script>
    {% endblock javascript %}
        
    

online_newspaper/main/templates/back/news_edit.html
    {% extends 'back/master.html' %}
    {% load static %}

    {% block headblock %}
        <script src="{% static 'back/ckeditor/ckeditor.js' %}"></script>
    {% endblock headblock %}

    {% block body %}
        <!-- Page content -->
        <div id="page-content">
            <!-- Datatables Content -->
            <div class="block full">
                <div class="block-title">
                    <h2><strong>News</strong> Edit</h2>
                </div>
                <p>You can Edit a news article from here.</p>
                <!-- Input Grid Content -->
                    <form action="{% url 'news:news-edit' pk %}" method="post" enctype='multipart/form-data' class="form-horizontal form-bordered">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-8">
                                <input type="text" id='newstitle' value='{{news.name}}' name='newstitle' class="form-control" placeholder="News Title">
                            </div>
                            <div class="col-md-4">
                                <select id="newscat" name="newscat" class="select-chosen" data-placeholder="{{news.category}}" style="width: 250px;">
                                    
                                    <option value="{{news.category_id}}">{{news.category}}</option>
                                    
                                    {% for option in subcategory %}
                                        <option value="{{option.pk}}">{{option.category_name}} | {{option.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea type="text" id='newstxtshort' value='{{news.short_text}}' name='newstxtshort' rows=5 class="form-control" placeholder="">{{news.short_text}}</textarea>
                            </div>
                        </div>

                        <script>
                            CKEDITOR.replace('newstxtshort');
                        </script>

                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea type="textarea" id='newstxtlong' value='' name='newstxtlong' rows=5 class="form-control" placeholder="">{{news.long_text}}</textarea>
                            </div>
                        </div>
                        <script>
                            CKEDITOR.replace('newstxtlong');
                        </script>

                        <div class="form-group">
                            <div class="col-md-6">
                                <input type="file" id='myfile' name='myfile' class="form-control" placeholder="Body Text">
                            </div>
                            <div class="col-md-6">
                                <img style='height: 233px; width:233px; border-radius: 5px' src="{{news.picture_url}}" alt="" srcset="">
                            </div>
                        </div>
                        
                        <div class="form-group form-actions">
                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-block btn-secondary">Submit</button>
                            </div>
                        </div>

                        
                    </form>
                    <!-- END Input Grid Content -->  
            </div>
            <!-- END Datatables Content -->
        </div>
        <!-- END Page Content -->
    {% endblock body %}

        
    {% block javascript %}
        <!-- Load and execute javascript code used only in this page -->
        <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
        <script>$(function(){ TablesDatatables.init(); });</script>
    {% endblock javascript %}
        
    

online_newspaper/main/templates/back/news_list.html
    {% extends 'back/master.html' %}
    {% load static %}

    {% block body %}
        <!-- Page content -->
        <div id="page-content">
            <!-- Datatables Content -->
            <div class="block full">
                <div class="block-title">
                    <h2><strong>News</strong> List</h2>
                </div>
                <p>You can add, delete, edit your data.</p>

                <div class="table-responsive">
                    <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                        <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th class="text-center"><i class="gi gi-user"></i></th>
                                <th>Title</th>
                                <th>Image</th>
                                <th>Date & Time</th>
                                <th>Category</th>
                                <th class="text-center">Views</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for news in news %}
                            <tr>
                                <td class="text-center">{{news.pk}}</td>
                                <td class="text-center"><img src="{% static 'back/img/placeholders/avatars/avatar15.jpg' %}" alt="avatar" class="img-circle"></td>
                                <td>{{news.short_text | safe}}</td>
                                <td class='text-center'><a href="javascript:void(0)"><img style='height: 55px; width:55px;' src="{{ news.picture_url }}" alt="avatar" class="img-circle"></a></td>
                                <td>{{news.publish_date}} | {{news.publish_time}}</td>
                                <td><span class="label label-info">{{news.category}}</span></td>
                                <td>{{news.views}}</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="{% url 'news:news-edit' pk=news.pk %}" data-toggle="tooltip" title="Edit" class="btn btn-xs btn-default"><i class="fa fa-pencil"></i></a>
                                        <a href="{% url 'news:news-delete' pk=news.pk %}" data-toggle="tooltip" title="Delete" class="btn btn-xs btn-danger"><i class="fa fa-times"></i></a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}    
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END Datatables Content -->
        </div>
        <!-- END Page Content -->
    {% endblock body %}

        
    {% block javascript %}
        <!-- Load and execute javascript code used only in this page -->
        <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
        <script>$(function(){ TablesDatatables.init(); });</script>
    {% endblock javascript %}
        
    

online_newspaper/main/templates/back/subcategory_add.html
    {% extends 'back/master.html' %}
    {% load static %}

    {% block body %}
        <!-- Page content -->
        <div id="page-content">
            <!-- Datatables Content -->
            <div class="block full">
                <div class="block-title">
                    <h2><strong>Sub Category</strong> Add</h2>
                </div>
                <p>You can Add a sub category from here.</p>
                <!-- Input Grid Content -->
                    <form action="{% url 'subcategory:subcategory-add' %}" method="post" enctype='multipart/form-data' class="form-horizontal form-bordered">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-8">
                                <input type="text" id='subcategory_name' name='subcategory_name' class="form-control" placeholder="Category Name">
                            </div>

                            <div class="col-md-4">
                                <select id="newscat" name="newscat" class="select-chosen" data-placeholder="Category" style="width: 250px;">
                                    {% for option in category %}
                                        <option value="{{option.pk}}">{{option.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>

                        </div>

                        <div class="form-group">

                            <div class="col-md-8"></div>
                            
                            <div class="col-md-4 text-center">
                                <button type="submit" class="btn btn-block btn-secondary">Submit</button>
                            </div>


                        </div>
                    </form>
                    <!-- END Input Grid Content -->  
            </div>
            <!-- END Datatables Content -->
        </div>
        <!-- END Page Content -->
    {% endblock body %}

        
    {% block javascript %}
        <!-- Load and execute javascript code used only in this page -->
        <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
        <script>$(function(){ TablesDatatables.init(); });</script>
    {% endblock javascript %}
        
    

online_newspaper/main/templates/back/subcategory_list.html
    {% extends 'back/master.html' %}
    {% load static %}

    {% block body %}
        <!-- Page content -->
        <div id="page-content">
            <!-- Datatables Content -->
            <div class="block full">
                <div class="block-title">
                    <h2><strong>Sub Category</strong> List</h2>
                </div>
                <p>You can add, delete, edit your sub category.</p>

                <div class="table-responsive">
                    <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                        <thead>
                            <tr >
                                <th class="text-center">ID</th>
                                <th class='text-center'>Category</th>
                                <th class='text-center'>Sub Category</th>
                                <th class='text-center'>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for subcategory in subcategory %}
                            <tr>
                                <td class="text-center">{{subcategory.pk}}</td>
                                <td class='text-center'>{{subcategory.category_name}}</td>
                                <td class='text-center'>{{subcategory.name}}</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-xs btn-default"><i class="fa fa-pencil"></i></a>
                                        <a href="" data-toggle="tooltip" title="Delete" class="btn btn-xs btn-danger"><i class="fa fa-times"></i></a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}    
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END Datatables Content -->
        </div>
        <!-- END Page Content -->
    {% endblock body %}

        
    {% block javascript %}
        <!-- Load and execute javascript code used only in this page -->
        <script src="{% static 'back/js/pages/tablesDatatables.js' %}"></script>
        <script>$(function(){ TablesDatatables.init(); });</script>
    {% endblock javascript %}
        
    