online_newspaper/main/urls.py
from django.conf.urls import url
from . import views


app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='main-index'),
    url(r'^panel/$', views.panel, name='admin-panel'),
    url(r'^about/$', views.about, name='main-about'),
]

online_newspaper/news/urls.py
from django.conf.urls import url
from . import views


app_name='news'
urlpatterns = [
    url(r'^news/(?P<pk>\d+)/$', views.news_details, name='news-details'),
    url(r'^panel/news/list/$', views.news_list, name='news-list'),
    url(r'^panel/news/add/$', views.news_add, name='news-add'),
    url(r'^panel/news/del/(?P<pk>\d+)/$', views.news_delete, name='news-delete'),
    url(r'^panel/news/edit/(?P<pk>\d+)/$', views.news_edit, name='news-edit'),
]

online_newspaper/online_newspaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('news.urls')),
    path('', include('category.urls')),
    path('', include('subcategory.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_newspaper/main/models.py
from __future__ import unicode_literals
from django.db import models


class Main(models.Model):
    name = models.CharField(max_length=21)
    fb = models.CharField(default='-', max_length=21)
    tw = models.CharField(default='-', max_length=21)
    yt = models.CharField(default='-', max_length=21)
    contact = models.CharField(default='-', max_length=21)
    about = models.TextField(default='-')

    set_name = models.CharField(default='Site Settings', max_length=21)

    def __str__(self):
        return self.set_name + " | " + str(self.pk)

online_newspaper/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Main
from news.models import News


def index(request):
    site = Main.objects.all()
    news = News.objects.all()
    return render(request, 'front/main/index.html', {'site': site, 'news': news})


def panel(request):
    return render(request, 'back/index.html')


def about(request):
    return render(request, 'front/main/about.html')

online_newspaper/main/templates/front/main/about.html
{% extends 'front/main/master.html' %}
{% load static %}

{% block body %}
	<!-- Breadcrumb -->
	<div class="container">
		<div class="headline bg0 flex-wr-sb-c p-rl-20 p-tb-8">
			<div class="f2-s-1 p-r-30 m-tb-6">
				<a href="index.html" class="breadcrumb-item f1-s-3 cl9">
					Home 
				</a>

				<span class="breadcrumb-item f1-s-3 cl9">
					About Us
				</span>
			</div>

			<div class="pos-relative size-a-2 bo-1-rad-22 of-hidden bocl11 m-tb-6">
				<input class="f1-s-1 cl6 plh9 s-full p-l-25 p-r-45" type="text" name="search" placeholder="Search">
				<button class="flex-c-c size-a-1 ab-t-r fs-20 cl2 hov-cl10 trans-03">
					<i class="zmdi zmdi-search"></i>
				</button>
			</div>
		</div>
	</div>

	<!-- Page heading -->
	<div class="container p-t-4 p-b-35">
		<h2 class="f1-l-1 cl2">
			About Us
		</h2>
	</div>

	<!-- Content -->
	<section class="bg0 p-b-110">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-8 p-b-30">
					<div class="p-r-10 p-r-0-sr991">
						<p class="f1-s-11 cl6 p-b-25">
							Curabitur volutpat bibendum molestie. Vestibulum ornare gravida semper. Aliquam a dui suscipit, fringilla metus id, maximus leo. Vivamus sapien arcu, mollis eu pharetra vitae, condimentum in orci. Integer eu sodales dolor. Maecenas elementum arcu eu convallis rhoncus. Donec tortor sapien, euismod a faucibus eget, porttitor quis libero. 
						</p>

						<p class="f1-s-11 cl6 p-b-25">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet est vel orci luctus sollicitudin. Duis eleifend vestibulum justo, varius semper lacus condimentum dictum. Donec pulvinar a magna ut malesuada. In posuere felis diam, vel sodales metus accumsan in. Duis viverra dui eu pharetra pellentesque. Donec a eros leo. Quisque sed ligula vitae lorem efficitur faucibus. Praesent sit amet imperdiet ante. Nulla id tellus auctor, dictum libero a, malesuada nisi. Nulla in porta nibh, id vestibulum ipsum. Praesent dapibus tempus erat quis aliquet. Donec ac purus id sapien condimentum feugiat.
						</p>

						<p class="f1-s-11 cl6 p-b-25">
							Praesent vel mi bibendum, finibus leo ac, condimentum arcu. Pellentesque sem ex, tristique sit amet suscipit in, mattis imperdiet enim. Integer tempus justo nec velit fringilla, eget eleifend neque blandit. Sed tempor magna sed congue auctor. Mauris eu turpis eget tortor ultricies elementum. Phasellus vel placerat orci, a venenatis justo. Phasellus faucibus venenatis nisl vitae vestibulum. Praesent id nibh arcu. Vivamus sagittis accumsan felis, quis vulputate
						</p>
					</div>
				</div>
				
				<!-- Sidebar -->
				<div class="col-md-5 col-lg-4 p-b-30">
					<div class="p-l-10 p-rl-0-sr991 p-t-5">
						<!-- Popular Posts -->
						<div>
							<div class="how2 how2-cl4 flex-s-c">
								<h3 class="f1-m-2 cl3 tab01-title">
									Popular Post
								</h3>
							</div>

							<ul class="p-t-35">
								<li class="flex-wr-sb-s p-b-30">
									<a href="#" class="size-w-10 wrap-pic-w hov1 trans-03">
										<img src="{% static 'front/images/popular-post-04.jpg' %}" alt="IMG">
									</a>

									<div class="size-w-11">
										<h6 class="p-b-4">
											<a href="#" class="f1-s-5 cl3 hov-cl10 trans-03">
												Donec metus orci, malesuada et lectus vitae
											</a>
										</h6>

										<span class="cl8 txt-center p-b-24">
											<a href="#" class="f1-s-6 cl8 hov-cl10 trans-03">
												Music
											</a>

											<span class="f1-s-3 m-rl-3">
												-
											</span>

											<span class="f1-s-3">
												Feb 18
											</span>
										</span>
									</div>
								</li>

								<li class="flex-wr-sb-s p-b-30">
									<a href="#" class="size-w-10 wrap-pic-w hov1 trans-03">
										<img src="{% static 'front/images/popular-post-05.jpg' %}" alt="IMG">
									</a>

									<div class="size-w-11">
										<h6 class="p-b-4">
											<a href="#" class="f1-s-5 cl3 hov-cl10 trans-03">
												Donec metus orci, malesuada et lectus vitae
											</a>
										</h6>

										<span class="cl8 txt-center p-b-24">
											<a href="#" class="f1-s-6 cl8 hov-cl10 trans-03">
												Game
											</a>

											<span class="f1-s-3 m-rl-3">
												-
											</span>

											<span class="f1-s-3">
												Feb 16
											</span>
										</span>
									</div>
								</li>

								<li class="flex-wr-sb-s p-b-30">
									<a href="#" class="size-w-10 wrap-pic-w hov1 trans-03">
										<img src="{% static 'front/images/popular-post-06.jpg' %}" alt="IMG">
									</a>

									<div class="size-w-11">
										<h6 class="p-b-4">
											<a href="#" class="f1-s-5 cl3 hov-cl10 trans-03">
												Donec metus orci, malesuada et lectus vitae
											</a>
										</h6>

										<span class="cl8 txt-center p-b-24">
											<a href="#" class="f1-s-6 cl8 hov-cl10 trans-03">
												Celebrity
											</a>

											<span class="f1-s-3 m-rl-3">
												-
											</span>

											<span class="f1-s-3">
												Feb 12
											</span>
										</span>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Back to top -->
	<div class="btn-back-to-top" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<span class="fas fa-angle-up"></span>
		</span>
	</div>

{% endblock body %}

online_newspaper/main/templates/front/main/index.html
{% extends 'front/main/master.html' %}
{% load static %} 
{% block title %}
	{%for site_detail in site %} 
		{{site_detail.name}} | Home 
	{% endfor %} 
{% endblock title %} 

{% block body %}
<!-- Feature post -->
<section class="bg0">
  <div class="row m-rl-0 justify-content-center">
    <div class="col-md-4 p-rl-1 p-b-2">
      <div
        class="bg-img1 size-a-11 how1 pos-relative"
        style="background-image: url({% static 'front/images/post-01.jpg'%})">
        <a
          href="blog-detail-02.html"
          class="dis-block how1-child1 trans-03">
		</a>

        <div class="flex-col-e-s s-full p-rl-25 p-tb-18">
          <a
            href="#"
            class="dis-block how1-child2 f1-s-2 cl0 bo-all-1 bocl0 hov-btn1 trans-03 p-rl-5 p-t-2">
            Technology
          </a>

          <h3 class="how1-child2 m-t-14 m-b-10">
            <a
              href="blog-detail-02.html"
              class="f1-l-1 cl0 hov-cl10 trans-03 respon1">
              Microsoft quisque at ipsum vel orci eleifend ultrices
            </a>
          </h3>
        </div>
      </div>
    </div>

    <div class="col-md-4 p-rl-1 p-b-2">
      <div
        class="bg-img1 size-a-11 how1 pos-relative"
        style="background-image: url({% static 'front/images/post-19.jpg'%})">
        <a
          href="blog-detail-02.html"
          class="dis-block how1-child1 trans-03">
		</a>

        <div class="flex-col-e-s s-full p-rl-25 p-tb-18">
          <a
            href="#"
            class="dis-block how1-child2 f1-s-2 cl0 bo-all-1 bocl0 hov-btn1 trans-03 p-rl-5 p-t-2">
            Technology
          </a>

          <h3 class="how1-child2 m-t-14 m-b-10">
            <a
              href="blog-detail-02.html"
              class="f1-l-1 cl0 hov-cl10 trans-03 respon1">
              London ipsum dolor sit amet, consectetur adipiscing elit.
            </a>
          </h3>
        </div>
      </div>
    </div>

    <div class="col-md-4 p-rl-1 p-b-2">
      <div
        class="bg-img1 size-a-11 how1 pos-relative"
        style="background-image: url({% static 'front/images/post-20.jpg'%})">
        <a
          href="blog-detail-02.html"
          class="dis-block how1-child1 trans-03">
		</a>

        <div class="flex-col-e-s s-full p-rl-25 p-tb-18">
          <a
            href="#"
            class="dis-block how1-child2 f1-s-2 cl0 bo-all-1 bocl0 hov-btn1 trans-03 p-rl-5 p-t-2">
            Life Style
          </a>

          <h3 class="how1-child2 m-t-14 m-b-10">
            <a
              href="blog-detail-02.html"
              class="f1-l-1 cl0 hov-cl10 trans-03 respon1">
              Pellentesque dui nibh, pellentesque ut dapibus ut
            </a>
          </h3>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Post -->
<section class="post bg0 p-t-85">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 col-lg-12">
        <div class="p-r-10 p-rl-0-sr991 p-b-20">
          <!-- Life Style  -->
          <div class="p-b-25 m-r--10 m-r-0-sr991">
            <div class="how2 how2-cl5 flex-s-c m-r-10 m-r-0-sr991">
              <h3 class="f1-m-2 cl17 tab01-title">Life Style</h3>
            </div>

            <div class="row p-t-35">
              <div class="col-sm-6 p-r-25 p-r-15-sr991">
                <!-- Item post -->
                <div class="flex-wr-sb-s m-b-30">
                  <a
                    href="blog-detail-02.html"
                    class="size-w-1 wrap-pic-w hov1 trans-03">
                    <img
                      src="{% static 'front/images/post-25.jpg' %}"
                      alt="IMG" />
                  </a>

                  <div class="size-w-2">
                    <h5 class="p-b-5">
                      <a
                        href="blog-detail-02.html"
                        class="f1-s-5 cl3 hov-cl10 trans-03">
                        Donec metus orci, malesuada et lectus vitae
                      </a>
                    </h5>

                    <span class="cl8">
                      <a href="#" class="f1-s-6 cl8 hov-cl10 trans-03">
                        Beach
                      </a>

                      <span class="f1-s-3 m-rl-3"> - </span>

                      <span class="f1-s-3"> Feb 17 </span>
                    </span>
                  </div>
                </div>

                <!-- Item post -->
                <div class="flex-wr-sb-s m-b-30">
                  <a
                    href="blog-detail-02.html"
                    class="size-w-1 wrap-pic-w hov1 trans-03">
                    <img
                      src="{% static 'front/images/post-26.jpg' %}"
                      alt="IMG"/>
                  </a>

                  <div class="size-w-2">
                    <h5 class="p-b-5">
                      <a
                        href="blog-detail-02.html"
                        class="f1-s-5 cl3 hov-cl10 trans-03">
                        Donec metus orci, malesuada et lectus vitae
                      </a>
                    </h5>

                    <span class="cl8">
                      <a href="#" class="f1-s-6 cl8 hov-cl10 trans-03">
                        Flights
                      </a>

                      <span class="f1-s-3 m-rl-3"> - </span>

                      <span class="f1-s-3"> Feb 16 </span>
                    </span>
                  </div>
                </div>
              </div>

              <div class="col-sm-6 p-r-25 p-r-15-sr991">
                <!-- Item post -->
                <div class="flex-wr-sb-s m-b-30">
                  <a
                    href="blog-detail-02.html"
                    class="size-w-1 wrap-pic-w hov1 trans-03">
                    <img
                      src="{% static 'front/images/post-03.jpg' %}"
                      alt="IMG"/>
                  </a>

                  <div class="size-w-2">
                    <h5 class="p-b-5">
                      <a
                        href="blog-detail-02.html"
                        class="f1-s-5 cl3 hov-cl10 trans-03">
                        Donec metus orci, malesuada et lectus vitae
                      </a>
                    </h5>

                    <span class="cl8">
                      <a href="#" class="f1-s-6 cl8 hov-cl10 trans-03">
                        Beachs
                      </a>

                      <span class="f1-s-3 m-rl-3"> - </span>

                      <span class="f1-s-3"> Feb 17 </span>
                    </span>
                  </div>
                </div>

                <!-- Item post -->
                <div class="flex-wr-sb-s m-b-30">
                  <a
                    href="blog-detail-02.html"
                    class="size-w-1 wrap-pic-w hov1 trans-03"
                  >
                    <img
                      src="{% static 'front/images/post-27.jpg' %}"
                      alt="IMG"
                    />
                  </a>

                  <div class="size-w-2">
                    <h5 class="p-b-5">
                      <a
                        href="blog-detail-02.html"
                        class="f1-s-5 cl3 hov-cl10 trans-03"
                      >
                        Donec metus orci, malesuada et lectus vitae
                      </a>
                    </h5>

                    <span class="cl8">
                      <a href="#" class="f1-s-6 cl8 hov-cl10 trans-03">
                        Flight
                      </a>

                      <span class="f1-s-3 m-rl-3"> - </span>

                      <span class="f1-s-3"> Feb 16 </span>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Latest -->
<section class="bg0 p-t-60 p-b-40">
  <div class="container">
    <div class="how2 how2-cl4 flex-s-c">
      <h3 class="f1-m-2 cl3 tab01-title">Latest News</h3>
    </div>

    <div class="row p-t-35">

      {% for latest in news %}
      <div class="col-sm-6 col-md-4">
        <!-- Item latest -->
        <div class="m-b-45">
          <a href="{% url 'news:news-details' pk=latest.pk %}" class="wrap-pic-w hov1 trans-03">
            <img src="{{latest.picture_url}}" alt="IMG" />
          </a>

          <div class="p-t-16">
            <h5 class="p-b-5">
              <a
                href="{% url 'news:news-details' pk=latest.pk %}"
                class="f1-m-3 cl2 hov-cl10 trans-03">
                {{latest.short_text|safe}}
              </a>
            </h5>

            <span class="cl8">
              <a href="{% url 'news:news-details' pk=latest.pk %}" class="f1-s-4 cl8 hov-cl10 trans-03">
                by {{latest.writer}}
              </a>

              <span class="f1-s-3 m-rl-3"> - </span>

              <span class="f1-s-3"> {{latest.publish_date}} </span>
            </span>
          </div>
        </div>
      </div>
      {% empty %}
        <div class="container text-center">
          <div class="jumbotron">
            <h3>No news has been added Yet!Please add a news</h3>
          </div>
        </div>
      {% endfor %}

    </div>
  </div>
</section>

<!-- Back to top -->
<div class="btn-back-to-top" id="myBtn">
  <span class="symbol-btn-back-to-top">
    <span class="fas fa-angle-up"></span>
  </span>
</div>

{% endblock body %}

online_newspaper/main/templates/front/main/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}{% endblock title %}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'front/images/icons/favicon.png' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'front/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'front/fonts/fontawesome-5.0.8/css/fontawesome-all.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'front/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'front/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'front/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'front/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'front/css/util.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'front/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body class="animsition">

 {% include 'front/main/partials/_header.html' %}

 {% block body %}



 {% endblock body %}


 {% include 'front/main/partials/_footer.html' %}

<!--===============================================================================================-->
	<script src="{% static 'front/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'front/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'front/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'front/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'front/js/main.js' %}"></script>

</body>
</html>